### ISSUE TITLE
Allow easier configuration of GCP project

### ISSUE THREAD

**Issue by MarkEdmondson1234** [andodet/googlePubsubR#11]
It would be helpful if you can pass in the project to say `topics_create()` as in some situations the project you are in is not the same as the PubSub topic and it involves awkward (`Sys.setenv("")`) to change it in the code.  I have a similar situation in `googleCloudRunner` and use the env variabels as defaults but let users set them also via say `cr_project_set()`

```r
cr_project_set <- function(projectId){

  .cr_env$project <- projectId

  myMessage("ProjectId set to", .cr_env$project, level = 3)
  .cr_env$project
}
```

**Comment by andodet** [comment]
This makes sense. Do you suggest exposing something like your function as the **only** way to interact with project setting? If so, I think it would open the opportunity to trim `project` from all function arguments.

Guess the above would lead to the following pattern
```r
topics_create("my_topic")
# Switch project and create same topic
ps_set_project("new-project")
topics_create("my_topic")
```

**Comment by MarkEdmondson1234** [comment]
Your choice, I have both available in `googleCloudRunner` but set it as default all the time with `cr_project_get()` - I think it gets the best of both worlds as for most uses you can set it and forget it in the .Renviron, but then change it on the fly for the situations like this one. 

From https://github.com/MarkEdmondson1234/googleCloudRunner/blob/master/R/init.R

```r
.cr_env <- new.env(parent = emptyenv())

#' Get/Set the projectId for your CloudRun services
#'
#' Can also use environment argument GCE_DEFAULT_PROJECT_ID
#'
#' @param projectId The projectId
#' @import assertthat
#' @export
#' @examples
#'
#' cr_project_get()
cr_project_set <- function(projectId){

  .cr_env$project <- projectId

  myMessage("ProjectId set to", .cr_env$project, level = 3)
  .cr_env$project
}

#' @rdname cr_project_set
#' @export
cr_project_get <- function(){

  if(!is.null(.cr_env$project)){
    return(.cr_env$project)
  }

  if(Sys.getenv("GCE_DEFAULT_PROJECT_ID") != ""){
    .cr_env$project <- Sys.getenv("GCE_DEFAULT_PROJECT_ID")
  }
  if(is.null(.cr_env$project)){
    stop("No projectId set - use cr_project_set() or env arg GCE_DEFAULT_PROJECT_ID",
         call. = FALSE)
  }
  .cr_env$project
}
```

**Comment by andodet** [comment]
Thanks a lot for the code sample, I will definitely include something like this in `v0.0.3`. I agree this greatly helps in multi-project scenarios.
