### ISSUE TITLE
Make startup quieter if not configured?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [andodet/googlePubsubR#12]
If the env vars are not set I get messages to set it up, but the problem is this is happening when I am importing `googleCloudRunner` as a Depends, and its not clear where the message comes from:

```r
library(googleCloudRunner)
! GCP_PROJECT environment not found, please set it up before starting!
! GCP_AUTH_FILE environment not found, please set it up before authenticating
✓ Setting scopes to https://www.googleapis.com/auth/cloud-platform
✓ Successfully auto-authenticated via /Users/mark/auth-googleCloudRunner.json
```

Could the messages occur if say an API call is not authenticated, and a note on its `googlePusubR` generating them?  I think perhaps moving them to .onAttach or using some conditional `suppressStartupMessages()` may do it.  I think I try to send a message when you are authenticated, but not when you are not.

**Comment by andodet** [comment]
I can see how this is annoying. It will be resolved in the next release by using `onAttach` instead of `onLoad`.
