### ISSUE TITLE
Change to this package name

### ISSUE THREAD

**Issue by MarkEdmondson1234** [andodet/googlePubsubR#6]
I know its shamelessly copy-pasted, but I think it would be good to have this package name in the user message instead ;)

https://github.com/andodet/googlePubsubR/blob/4fa25a0c937c6d69ad872d52dc42f6e1174d5eea/R/auth.R#L22

**Comment by andodet** [comment]
Definitely overlooked this while stitching up authentication to start developing. Do you suggest to just change the function argument or is there anything else?

If that's the case, I can push this in a new release alongside a few minor fixes to documentation in a week or so. Feel free to suggest anything else that might help to flash out `googleAuthR` paternity.

**Comment by MarkEdmondson1234** [comment]
Yep it just determines what text users see when they auth the first time.
