### ISSUE TITLE
Fix msg_encode example

### ISSUE THREAD

**Issue by MarkEdmondson1234** [andodet/googlePubsubR#9]
The first example didnt' work for me, missing function?

```r
library(googlePubsubR)
> library(base64enc)
> library(jsonlite)
> mtcars %>%
+     toJSON(auto_unbox = TRUE) %>%
+     # Pub/Sub expects a base64 encoded string
+     msg_encode() %>% 
+     PubsubMessage() 
Error in msg_encode(.) : could not find function "msg_encode"
```

**Comment by andodet** [comment]
That seems strange, msg_decode and msg_encode are exported in utils.R and
can also be found in NAMESPACE. I'll debug it further asap

**Comment by MarkEdmondson1234** [comment]
I was running CRAN version if that makes a difference: googlePubsubR_0.0.1

**Comment by andodet** [comment]
Uh, got it. I've pushed a quick 0.0.2 update to CRAN to correct app name in `pubsub_auth` and added couple helpers to encode/decode messages. Try an `update.packages`, that should do the trick.

**Comment by MarkEdmondson1234** [comment]
I updated to version 0.0.2 and the above code works!

...but the code in the function example within the \dontrun block does not:

```r
mtcars %>% 
  msg_encode() %>% 
  PubsubMessage()

# Error in charToRaw(.) : argument must be a character vector of length 1
```

**Comment by andodet** [comment]
Glad it's all sorted. Will keep this open as I'll fix the example in a future release, I completely overlooked it.
